services:
  db-container:
    image: mysql:9.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema/init.sql:docker-entrypoint-initdb.d:init.sql

  java-app:
    build: .
    container_name: test-comment-app
    depends_on:
      - db-container
    networks:
      - app-network
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

networks:
  app-network:
    driver: bridge
